version: '3.8'

services:
  web:
    container_name: web-api
    build: .
    volumes:
      - .:/app
    ports:
      - 8501:8501
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0