version: '3.8'

services:
  app:
    container_name: reppie-labs-summarization
    build: ../../.
    volumes:
      - ../../:/reppie-labs
    ports:
      - 8502:8502
    command: streamlit run summarization/sales/app.py --server.port=8502 --server.address=0.0.0.0
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=5
      - OPENAI_API_KEY=<YOUR OPENAI_API_KEY>